### ISSUE TITLE
Implement more informations

### ISSUE THREAD

**Issue by TimoBS** [magic21nrw/MMM-COVID19-AMPEL#1]
Most Magic Mirror module related to Covid-19 do focus only on country and does not help in actual situation.
Therefore I'm very happy to found your module - thanks for that!
But I have a widget running on iOS which gave a very brief, nice and easy overview about the situation in the city, state and country including a nice GUI.

You may check and consider if you're able to fork or implement such equal functions and GUI in your Magic Mirror module the following source: https://github.com/rphl/corona-widget

What I´m missing if I compare both are:
- total amount of actual cases in country
- actual amount of cases in my city

Thanks in advance and greetings!

**Comment by magic21nrw** [comment]
Hi,

interesting topic. Lets see what we can do here. In my opinion a mere number of infections does not really give any meaningful statement. In Munich, we have 19.028 people as today. But is this a lot or do I need to be extra careful? Hm, it would make sense to include the % of population of the city and display this as well. This shows the possibility that I meet an infected person per 100 persons met.

This would focus more on the local city than on the whole country. Does this make most sense?

**Comment by TimoBS** [comment]
Was only an suggestion and idea that the "code" is already existing and may be could be easily transferred and show more interesting data. Personally I´m more interesting in those data. For my point of view the data actually used and displayed from RKI or NPGEO does anyhow not help you on a daily base because of the transmission delay from the city to RKI. All the time the incidence value differs from the actual/valid one of my city and for that I've to check anyhow the webpage of my hometown.

**Comment by magic21nrw** [comment]
Okay, I implemented additional information. Please pull new version.
