### ISSUE TITLE
Sorting by location / object ID

### ISSUE THREAD

**Issue by ThomasH-W** [magic21nrw/MMM-COVID19-AMPEL#10]
Hello, 
First of all many thanks for the module - it is exactly what I was looking for.

When selecting multiple locations in the confg file, it looks like that order is being determined by the absolute number of infections and the order of cityID's in the config file being ignored.
Would be nice if you could add an option to use the order in the config file.

Kind Regards
Thomas

**Comment by magic21nrw** [comment]
To be honest, I am not 100% sure on how I can do that (only a noob programmer ;) ) to map the order of my config to the order of my array. What I could do is to sort it alphabetically which could be done with one line of extra code. Would that help to order multiple locations in a meaningful way?

**Comment by ThomasH-W** [comment]
This update works for me as the main objectiv was to prevent a different order of city names each time.
Thank your.
