### ISSUE TITLE
Showing Munich only

### ISSUE THREAD

**Issue by RaoulDuke25** [magic21nrw/MMM-COVID19-AMPEL#11]
Changing cityID to either 16 (Hamburg) or 100 (Herford) will not overwrite default value. Only showing Munich.

`                {       module: "MMM-COVID19-AMPEL",                        position: "bottom_bar",     
                        cityID: ["100"],
                        },`

Tried either ` ["100" , "16"]` as well as` ["100" , "016"]`.

**Comment by magic21nrw** [comment]
It seems that your config.js is wrong. it is missing the " config:	{ ... " part...

Use this and apply your settings.


{
  module: 'MMM-COVID19-AMPEL',
  position: 'top_center',
  config:	{
    header: 'COVID-19 Inzidenzwert', // Header Title of Display on MagicMirror
    cityID: ["224","223"], // City ID from  https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/data
    infoRowClass: "small", // small, medium
    showUpdateDateInHeader: true, //Show update date in header
    showUpdateDateInRow: false, //Show update date in each row
    showStatusLightLeft: true, //Show left status light
    showStatusLightRight: true, // Show right status light
    showTitle: true, //Show Title row with headlines if you want to display more than one information
    showCases: true, //Show amount of active cases in city
    showCasesPerPeople: true, //Show Percentage of active cases per inhabitant
    showDeathRatePerPeople: true, //show death rate in % of infected people
    show7DayIncidence: true, // Show 7 day incidence value for your location
    landModeOnly: false, // Shows Bundesland instead of City in Bundesland (Thos who want to display only the Bundesland)
    numberOfDigits: 2, //Round the Percentage and incidence value to number of digits
    updateInterval: 3600000, // update interval in milliseconds // 1 Hour - Values are only refreshed every 24 H on Server
    fadeSpeed: 4000
	}
},
