### ISSUE TITLE
Display of cities, Bundesland and Germany at the same time

### ISSUE THREAD

**Issue by spitzlbergerj** [magic21nrw/MMM-COVID19-AMPEL#13]
Is it possible to display a line for the Bundesland and for Germany as a whole in addition to individual cities?

I briefly looked in the code, but did not find a quick way. Otherwise I would have started a pull request right away ;-) I'm sure you're better at the code, so maybe it's not so complicated.

It would be enough for me if one state (Bavaria) and Germany as a whole could be displayed additionally to three cities.

Thanks for this great module!

**Comment by magic21nrw** [comment]
Unfortunately it is not possible as the data source is not providing Bundesland and total Germany data. 
For this data you might need to add an additional module that gives more macro orientated data such as MMM-COVID.

**Comment by magic21nrw** [comment]
If you want to have the Bundesland only, please simply add the module twice and disable the headers. This should do the trick. But unfortunately the data source has no data point for Germany as a whole.

**Comment by spitzlbergerj** [comment]
Hi
unfortunately this is not the solution. The module then shows my three cities in the first instance and Bavaria three times in the second, even if I specify only one city there.
Nevertheless, thanks for the effort and for thinking.
