### ISSUE TITLE
Collision with other modules

### ISSUE THREAD

**Issue by Datenzentrale** [magic21nrw/MMM-COVID19-AMPEL#14]
Sadly I am verry stupid and can't find a solution to remove the line under the header, is there a way to remove it because it colides with another module...

**Comment by magic21nrw** [comment]
Not a real idea as this is a general feature of MagicMirror Header CSS styling. The line should only be as long as the width of the module itself. So if the screen is not large enough, reduce the information shown and it will get smaller.
