### ISSUE TITLE
Updateintetvall

### ISSUE THREAD

**Issue by lexnared** [magic21nrw/MMM-COVID19-AMPEL#17]
Hi.
It's possible to update the covid 19 every day at 4pm?

The actually settings in the config file.

​updateInterval​: ​3600000​,​ ​// update interval in milliseconds // 1 Hour - Values are only refreshed every 24 H on Server​
   
Do I understand correctly that COVIT 19 is updated only once a day?

**Comment by magic21nrw** [comment]
That is correct. 

The Module uses two data sources which are only updated once a day. Unfortunately the update takes place at random times and at completely different times of the day. Therefore setting it to one hour is sufficient and reasonable.
