### ISSUE TITLE
MM is black

### ISSUE THREAD

**Issue by DiWa2194** [magic21nrw/MMM-COVID19-AMPEL#19]
Hi,
I cloned the files from github and added the lines below to the config.js file, but the MM is completely black. config:check has no errors. If I comment out the lines, the MM is running with my modules.
Any suggestions how to fix it? Thanks.

{
			module: "MMM-COVID19-AMPEL",
			position: "top_center",
			config:	{
				header: "COVID-19 Inzidenzwert", // Header Title of Display on MagicMirror
				cityID: ["224","223"], // City ID from  https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/data
				infoRowClass: "small", // small, medium
				showUpdateDateInHeader: true, //Show update date in header
				showUpdateDateInRow: false, //Show update date in each row
				showStatusLightLeft: true, //Show left status light
				showStatusLightRight: true, // Show right status light
				showTitle: true, //Show Title row with headlines if you want to display more than one information
				showSKLK: true, //Show the Region information if the Pace displayed is the city or regional area (Stadt or Land)
				showCases: true, //Show amount of active cases in city
				showCasesPerPeople: true, //Show Percentage of active cases per inhabitant
				showDeathRatePerPeople: true, //show death rate in % of infected people
				show7DayIncidence: true, // Show 7 day incidence value for your location
				landModeOnly: false, // Shows Bundesland instead of City in Bundesland (Thos who want to display only the Bundesland)
				showVaccinations: true, //Shows the total quota of fist shots people got in the whole country in header
				numberOfDigits: 2, //Round the Percentage and incidence value to number of digits
				updateInterval: 3600000, // update interval in milliseconds // 1 Hour - Values are only refreshed every 24 H on Server
				fadeSpeed: 4000
			}
},

**Comment by magic21nrw** [comment]
Please get latest version with git pull and run npm install to install all necessary plugins (I updated the version just a few days ago to eliminate a bug with retrieving the file for vaccinations which requires another request module from npm). If this is missing it is not working. 

But other than that - module should work as desired.

**Comment by magic21nrw** [comment]
I added the info to git pull && npm install - for upgrading.  Please do that and try again. If it is not working - please open again with your syslog and log file attached including the messages when starting the magic mirror.

**Comment by DiWa2194** [comment]
Thanks, that did the trick! Great module!
