### ISSUE TITLE
City/county ID identification no longer possible (changed dataset structure?)

### ISSUE THREAD

**Issue by hweigel** [magic21nrw/MMM-COVID19-AMPEL#21]
Hello everybody,

the dataset structure appears to have changed, it is no longer showing the IDs (eg 224 for "Ingolstadt"), which are necessary to configure the module.

Link:  https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/data.

Would somebody have a new and/ or amended link they could share?

Thx a bunch
Helmut

**Comment by hweigel** [comment]
Update: there's a possible workaround by downloading the dataset as CSV, the first field contains the Object_ID.

**Comment by magic21nrw** [comment]
Hi,

sorry, I was busy the last week but fortunately the pull request was already done and the problem solved.

Thanks for contributing.

Daniel
