### ISSUE TITLE
request library is deprecated

### ISSUE THREAD

**Issue by codac** [magic21nrw/MMM-COVID19-AMPEL#22]
**Describe the bug**
The request library is deprecated and therefor has been removed as dependency of the current MM version.

**To Reproduce**
Run karsten13/magicmirror Docker, check the Protocol for errors
1. Config File
```
{
		        module: "MMM-COVID19-AMPEL",
		        position: "bottom_bar",
		        config:	{
		        	header: "COVID-19 Inzidenzwert", // Header Title of Display on MagicMirror
  		        	cityID: ["124","123","16"], // City ID from  https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/data
		        	infoRowClass: "small", // small, medium
		        	showUpdateDateInHeader: true, //Show update date in header
		        	showUpdateDateInRow: false, //Show update date in each row
		        	showStatusLightLeft: true, //Show left status light
		        	showStatusLightRight: true, // Show right status light
		        	showTitle: true, //Show Title row with headlines if you want to display more than one information
		        	showCases: true, //Show amount of active cases in city
		        	showCasesPerPeople: true, //Show Percentage of active cases per inhabitant
		        	showDeathRatePerPeople: true, //show death rate in % of infected people
		        	show7DayIncidence: true, // Show 7 day incidence value for your location
		        	numberOfDigits: 2, //Round the Percentage and incidence value to number of digits
		        	updateInterval: 3600000, // update interval in milliseconds // 1 Hour - Values are only refreshed every 24 H on Server
		        	fadeSpeed: 4000
		        }
		},
```
2. Additional Modules used
yes, but are not relevant here

**Expected behavior**
Module should be updated, without using the request library so that this error wont appear anymore.

**Screenshots**
see additional context

**Additional context**
Error messages are:
[15.07.2021 09:59.46.610] [ERROR] Whoops! There was an uncaught exception...
[15.07.2021 09:59.46.613] [ERROR] Error: Cannot find module 'request'
 code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/magic_mirror/modules/MMM-COVID19-AMPEL/node_helper.js',
    '/opt/magic_mirror/js/app.js',
    '/opt/magic_mirror/serveronly/index.js'
  ]
}
[15.07.2021 09:59.46.614] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[15.07.2021 09:59.46.614] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by magic21nrw** [comment]
Thanks, I replaced the request library with something new and maintained.

**Comment by codac** [comment]
perfect, thank you for the fast reply!
