### ISSUE TITLE
Anzeige der Inzidenz für das Bundesland

### ISSUE THREAD

**Issue by charraeus** [magic21nrw/MMM-COVID19-AMPEL#28]
Ist es auch möglich, Werte für ein Bundesland zusätzlich zu Städten anzuzeigen? Wie?

**Comment by magic21nrw** [comment]
Nein, das geht leider nicht. Hier das Modul ein zweites Mal im landmode only einfügen und untereinander anzeigen lassen. 

Vom mobilen Gerät gesendet, bitte entschuldigt ggf. Auto-Korrektur typos.

**Comment by charraeus** [comment]
Alles klar. Danke. Ich schließe das Issue.
