### ISSUE TITLE
Ein sehr schönes Modul, ich bin echt begeistert. Ist es irgendwie möglich die Zeilenhöhe zu verringern um mehrere Zeilen (mehrere Kreise) auf gleicher Höhe (Fläche) anzuzeigen? Der Platz auf meinem MM wird immer weniger ;-) Gruß KUP

### ISSUE THREAD

**Issue by kupraez** [magic21nrw/MMM-COVID19-AMPEL#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by magic21nrw** [comment]
Habe es etwas optimiert. Jetzt sollte mehr drauf passen.

**Comment by kupraez** [comment]
genau so.....fantastisch!
