### ISSUE TITLE
No update received yet - Module does not update

### ISSUE THREAD

**Issue by slemens** [magic21nrw/MMM-COVID19-AMPEL#8]
**Describe the bug**
Module seems not to get updates from its database, there is only "No update received yet" displayed
**To Reproduce**
Just install the module, with the sample config

1. Config 
	{
	  module: 'MMM-COVID19-AMPEL',
	  position: 'top_center',
	  header: 'COVID-19 Inzidenzwert', // Header Title of Display on MagicMirror
	  config:	{
		cityID: ["197","166","147","324"], // City ID from  https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/data
		infoRowClass: "small", // small, medium
		showUpdateDateInHeader: true, //Show update date in header
		showUpdateDateInRow: false, //Show update date in each row
		showStatusLightLeft: true, //Show left status light
		showStatusLightRight: true, // Show right status light
		showTitle: true, //Show Title row with headlines if you want to display more than one information
		showCases: true, //Show amount of active cases in city
		showCasesPerPeople: true, //Show Percentage of active cases per inhabitant
		showDeathRatePerPeople: true, //show death rate in % of infected people
		show7DayIncidence: true, // Show 7 day incidence value for your location
		numberOfDigits: 2, //Round the Percentage and incidence value to number of digits
		updateInterval: 3600000, // update interval in milliseconds // 1 Hour - Values are only refreshed every 24 H on Server
		fadeSpeed: 4000
	}
},

2. Additional Modules used
None 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by magic21nrw** [comment]
When I try to get the data for 324 Area, I get an error from the API as 324 seems not to be registered. This might cause the problem.
Please check and reopen if it still persists - at my mirror it is working as desired.

**Comment by magic21nrw** [comment]
I checked the config above with my mirror system and it loads the 4 regions without any problem. It seems that there is something wrong with your configuration. Please check your logs for further information.

**Comment by LeoTasmo** [comment]
i got the same problem with my mirror. No Update receive.

**Comment by Blackjack1880** [comment]
I have the same problem today. 
Any solutions?

**Comment by magic21nrw** [comment]
Post your config. Normally everything works.
