### ISSUE TITLE
show germany

### ISSUE THREAD

**Issue by NickOne81** [magic21nrw/MMM-COVID19-AMPEL#9]
Hi there,
is it somehow possible to display the whole of Germany, or even Berlin as a federal state. Berlin has too many districts to display them all individually. Thanks

**Comment by magic21nrw** [comment]
It is only possible to show the data from the data source. It has the Bundesland data which shows only the Bundesland. I added this feature by selecting landModeOnly: true. See Readme for more details.

**Comment by NickOne81** [comment]
Danke für das Einfügen. Leider funktioniert dann aber nur noch der Inzidenzwert. Alles andere wird mir nicht mehr angezeigt. Habe es mit München und Berlin ausprobiert.

**Comment by magic21nrw** [comment]
Ja, leider sind die Detaildaten auf bundeslandebene nicht verfügbar. Deshalb habe ich den Rest ausgeblendet.
